### ISSUE TITLE
example has different result

### ISSUE THREAD

**Issue by ncy0201** [dkaslovsky/GraphRole#16] opened 2024-06-18 01:41 UTC
When I run the example.ipynb, I get a different result.

![image](https://github.com/dkaslovsky/GraphRole/assets/108738017/1d5601e6-ff80-47d6-bafc-e0e54ccc55d2)

And my result different from #12 

I find the `feature_extractor.generation_count=2` in my code,
not `3` in the results of your run, I want to know it's why.

![image](https://github.com/dkaslovsky/GraphRole/assets/108738017/502b0131-e8ba-4813-b66a-a6253ce63252)

Thanks for your help.

**Comment by dkaslovsky** [comment] 2024-06-20 01:00
Hello, thank you for opening this issue and for using GraphRole!

To help me diagnose the underlying cause, would you be able to share as much information about your specific setup as possible?

In particular, any of the following might be helpful:
* Your operating system, including version
* The version of Python you are using
* The version of GraphRole you are using
* The list of dependency versions (the output of pip list or equivalent)
* Any other information that might be helpful that I haven't thought of

Thanks!

**Comment by ncy0201** [comment] 2024-06-20 01:36
Thanks for the reply, here is some of my config information：

![image](https://github.com/dkaslovsky/GraphRole/assets/108738017/1f1aede8-2c3a-424e-bbaf-148817fb12ab)

python == 3.11.5

graphrole == 1.1.1

networkx == 3.3

seaborn == 0.13.2

matplotlib == 3.9.0

numpy == 1.24.4

pandas == 1.5.3

**Comment by dkaslovsky** [comment] 2024-06-20 16:02
Thank you for the info, it will be helpful as I dig into this. I'll do my best to get you a timely answer, but it might take several days before I can devote some time here.

**Comment by ncy0201** [comment] 2024-06-21 01:06
Thank you so much for taking the time to look into this! I am very grateful for your help. If you need any additional information or any progress, please feel free to let me know. I will wait patiently for your reply.

thanks again!

**Comment by dkaslovsky** [comment] 2024-07-12 18:36
Hello. Thanks for your patience. I've been investigating this issue and will need a bit more time to pin down the root cause, but I have made some progress. Hoping for a more complete update soon. Thanks!

**Comment by dkaslovsky** [comment] 2024-07-12 20:47
Update: I've located the issue. The example graph (the karate club graph from NetworkX) is a weighted graph and GraphRole automatically uses edge weights in its feature computations if they are included. However, the examples were produced prior to the introduction of this capability. So, everything is being computed correctly. I've verified that the results in the example can be reproduced as expected by removing the weights from the graph. I'll push a change to the example soon, at which point I believe we can close out this issue as well as #12 .

Thank you so much for bringing this to my attention!

**Comment by ncy0201** [comment] 2024-07-13 02:10
I removed the weights of the edges using your solution, `RecursiveFeatureExtractor` extracted features are consistent with the example features.

<img src="https://github.com/user-attachments/assets/dcd96d4d-56ff-46e6-a989-f0d4920e2308" alt="image" width="500"/>

However, there are differences in the roles extracted by `RoleExtractor`.

<img src="https://github.com/user-attachments/assets/0fd0f61c-fc49-490d-b797-23bd3a1068e3" alt="image" width="500"/>

There are five roles in my result, it's why ?

<img src="https://github.com/user-attachments/assets/bad097a1-7cd6-4948-99d5-ad9038878704" alt="image" width="500"/>


I appreciate your help and look forward to your response. Thank you again for your time and assistance.

**Comment by dkaslovsky** [comment] 2024-07-13 15:11
Yes, I've noticed this as well and have tracked it down to differences in versions of scikit-learn and scipy. The versions used to be pinned but now only are lower-bounded, introduced in #14. I plan to update the example files comprehensively to at least note this if not fix it. Expect that change coming soon.

**Comment by dkaslovsky** [comment] 2024-07-13 19:58
#18 has been merged and should address all concerns here. Please let me know if you have any further questions. Thanks so much for your attention to detail!

**Closed as completed by dkaslovsky** 2024-07-13 19:58 UTC
